// Workflow states enum for the loan application process
export const WORKFLOW_STATES = {
  DRAFT: 'DRAFT',
  KYC_PENDING: 'KYC_PENDING',
  KYC_COMPLETED: 'KYC_COMPLETED',
  KYC_FAILED: 'KYC_FAILED',
  CREDIT_CHECK_PENDING: 'CREDIT_CHECK_PENDING',
  CREDIT_CHECK_COMPLETED: 'CREDIT_CHECK_COMPLETED',
  CREDIT_REJECTED: 'CREDIT_REJECTED',
  ELIGIBLE: 'ELIGIBLE',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
};

// Workflow state order for progression
export const WORKFLOW_ORDER = [
  WORKFLOW_STATES.DRAFT,
  WORKFLOW_STATES.KYC_PENDING,
  WORKFLOW_STATES.KYC_COMPLETED,
  WORKFLOW_STATES.CREDIT_CHECK_PENDING,
  WORKFLOW_STATES.CREDIT_CHECK_COMPLETED,
  WORKFLOW_STATES.ELIGIBLE,
];

// Terminal states (cannot proceed further)
export const TERMINAL_STATES = [
  WORKFLOW_STATES.KYC_FAILED,
  WORKFLOW_STATES.CREDIT_REJECTED,
  WORKFLOW_STATES.NOT_ELIGIBLE,
  WORKFLOW_STATES.ELIGIBLE,
];

// State display labels
export const STATE_LABELS = {
  [WORKFLOW_STATES.DRAFT]: 'Draft',
  [WORKFLOW_STATES.KYC_PENDING]: 'KYC Pending',
  [WORKFLOW_STATES.KYC_COMPLETED]: 'KYC Completed',
  [WORKFLOW_STATES.KYC_FAILED]: 'KYC Failed',
  [WORKFLOW_STATES.CREDIT_CHECK_PENDING]: 'Credit Check Pending',
  [WORKFLOW_STATES.CREDIT_CHECK_COMPLETED]: 'Credit Check Completed',
  [WORKFLOW_STATES.CREDIT_REJECTED]: 'Credit Rejected',
  [WORKFLOW_STATES.ELIGIBLE]: 'Eligible',
  [WORKFLOW_STATES.NOT_ELIGIBLE]: 'Not Eligible',
};

// State colors for UI
export const STATE_COLORS = {
  [WORKFLOW_STATES.DRAFT]: 'bg-gray-100 text-gray-800',
  [WORKFLOW_STATES.KYC_PENDING]: 'bg-yellow-100 text-yellow-800',
  [WORKFLOW_STATES.KYC_COMPLETED]: 'bg-green-100 text-green-800',
  [WORKFLOW_STATES.KYC_FAILED]: 'bg-red-100 text-red-800',
  [WORKFLOW_STATES.CREDIT_CHECK_PENDING]: 'bg-yellow-100 text-yellow-800',
  [WORKFLOW_STATES.CREDIT_CHECK_COMPLETED]: 'bg-green-100 text-green-800',
  [WORKFLOW_STATES.CREDIT_REJECTED]: 'bg-red-100 text-red-800',
  [WORKFLOW_STATES.ELIGIBLE]: 'bg-green-100 text-green-800',
  [WORKFLOW_STATES.NOT_ELIGIBLE]: 'bg-red-100 text-red-800',
};

// Employment types
export const EMPLOYMENT_TYPES = {
  SALARIED: 'SALARIED',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
};

export const EMPLOYMENT_LABELS = {
  [EMPLOYMENT_TYPES.SALARIED]: 'Salaried',
  [EMPLOYMENT_TYPES.SELF_EMPLOYED]: 'Self-Employed',
};

// Loan configuration constants
export const LOAN_CONFIG = {
  MIN_AGE: 21,
  MAX_LOAN_MULTIPLIER: 20, // Max loan = 20x monthly income
  INTEREST_RATE: 12, // 12% per annum
  TENURE_MONTHS: 36,
  SALARIED_MAX_EMI_PERCENT: 50,
  SELF_EMPLOYED_MAX_EMI_PERCENT: 40,
  MIN_CREDIT_SCORE: 650,
  MAX_ACTIVE_LOANS: 5,
  MIN_KYC_NAME_MATCH_SCORE: 80,
};
